"""Distillery training utilities (pure configs/math; optional torch is separate)."""

from __future__ import annotations

from distillery.training.artifacts import (
    RUN_ARTIFACT_LAYOUT,
    ArtifactLayout,
    build_run_artifact_layout,
    generate_load_instructions,
    materialization_sidecar,
    parse_sha256sums,
    verify_sha256sums,
    write_sha256sums,
)
from distillery.training.batching import (
    DEFAULT_FINANCE_MIXTURE,
    BatchPlan,
    MixtureSpec,
    SamplerExample,
    largest_remainder_counts,
    plan_batches,
    sampler_order_hash,
)
from distillery.training.entrypoint import (
    EXECUTE_ACKNOWLEDGEMENT,
    RESPONSE_FILE_EVIDENCE_KEY,
    EntrypointResult,
    ResponseFileEvidence,
    build_response_file_evidence,
    canonical_records_sha256,
    canonical_response_jsonl,
    capability_binding_sha256,
    length_configuration_sha256,
    main,
    model_configuration_sha256,
    run_entrypoint,
    training_configuration_sha256,
)
from distillery.training.losses import (
    forward_kl_chunked,
    forward_kl_full,
    hard_cross_entropy,
    log_softmax,
    mixed_kd_ce_loss,
    softmax,
)
from distillery.training.models import (
    FrozenTeacherRuntimeGuard,
    ModelRef,
    StudentLoadConfig,
    TeacherLoadConfig,
    TrainingLoadPlan,
    assert_runtime_teacher_frozen,
    assert_teacher_load_plan_frozen,
    build_student_load_config,
    build_teacher_load_config,
    build_training_load_plan,
    construct_optimizer_after_teacher_guard,
    freeze_and_assert_runtime_teacher,
)
from distillery.training.qlora import (
    DEFAULT_LORA_TARGET_MODULES,
    QLoRAConfig,
    QuantizationConfigSpec,
    qlora_from_manifest_dict,
    qlora_from_smoke_budget,
    qlora_from_training_budget,
)

# NOTE: distillery.training.torch_losses is intentionally not imported here.

__all__ = [
    "DEFAULT_FINANCE_MIXTURE",
    "DEFAULT_LORA_TARGET_MODULES",
    "ArtifactLayout",
    "BatchPlan",
    "EntrypointResult",
    "EXECUTE_ACKNOWLEDGEMENT",
    "RESPONSE_FILE_EVIDENCE_KEY",
    "FrozenTeacherRuntimeGuard",
    "ResponseFileEvidence",
    "assert_runtime_teacher_frozen",
    "assert_teacher_load_plan_frozen",
    "build_response_file_evidence",
    "capability_binding_sha256",
    "canonical_records_sha256",
    "canonical_response_jsonl",
    "construct_optimizer_after_teacher_guard",
    "MixtureSpec",
    "ModelRef",
    "QLoRAConfig",
    "QuantizationConfigSpec",
    "RUN_ARTIFACT_LAYOUT",
    "SamplerExample",
    "StudentLoadConfig",
    "TeacherLoadConfig",
    "TrainingLoadPlan",
    "build_run_artifact_layout",
    "build_student_load_config",
    "build_teacher_load_config",
    "build_training_load_plan",
    "forward_kl_chunked",
    "forward_kl_full",
    "freeze_and_assert_runtime_teacher",
    "generate_load_instructions",
    "hard_cross_entropy",
    "largest_remainder_counts",
    "length_configuration_sha256",
    "log_softmax",
    "main",
    "materialization_sidecar",
    "mixed_kd_ce_loss",
    "model_configuration_sha256",
    "parse_sha256sums",
    "plan_batches",
    "qlora_from_manifest_dict",
    "qlora_from_smoke_budget",
    "qlora_from_training_budget",
    "run_entrypoint",
    "sampler_order_hash",
    "softmax",
    "training_configuration_sha256",
    "verify_sha256sums",
    "write_sha256sums",
]
