"""Policy-gated local, Bedrock, and direct Anthropic teacher adapters."""

from distillery.teachers.adapters import (
    AnthropicAPIError,
    AnthropicClientFactory,
    AnthropicModelDiscovery,
    BedrockConverseTeacher,
    BedrockError,
    DirectAnthropicTeacher,
    LocalOpenWeightTeacher,
    OfficialAnthropicClientFactory,
)
from distillery.teachers.budget import RequestGovernor
from distillery.teachers.cache import ImmutableTeacherCache
from distillery.teachers.chain import PriorityTeacherChain, TeacherCandidate
from distillery.teachers.errors import TeacherError, TeacherErrorCode
from distillery.teachers.hashing import prompt_sha256, request_sha256
from distillery.teachers.policy import (
    PROJECT_PROVIDER_POLICY,
    PROJECT_PROVIDER_POLICY_VERSION,
    assert_request_allowed,
)
from distillery.teachers.protocol import TeacherGenerator
from distillery.teachers.secrets import (
    ANTHROPIC_SECRET_NAME,
    AnthropicSecretResolver,
    ChainedAnthropicSecretResolver,
    EnvironmentAnthropicSecretResolver,
    MacOSKeychainAnthropicSecretResolver,
)
from distillery.teachers.types import (
    AttestationSource,
    AuthorizationProvider,
    DerivedArtifactDisposition,
    GenerationSettings,
    HumanApproverAttestation,
    IntendedUse,
    LicenseStatus,
    OutputRetention,
    OutputStorage,
    RedistributionScope,
    ReviewStatus,
    StudentModelFamily,
    TeacherBudget,
    TeacherModelFamily,
    TeacherModelRef,
    TeacherProvider,
    TeacherRecipe,
    TeacherRequest,
    TeacherResult,
    ToolSpec,
    WrittenAuthorizationEvidence,
    seal_license_disposition,
    seal_output_use_policy,
    seal_written_authorization,
)

__all__ = [
    "ANTHROPIC_SECRET_NAME",
    "PROJECT_PROVIDER_POLICY",
    "PROJECT_PROVIDER_POLICY_VERSION",
    "AttestationSource",
    "AuthorizationProvider",
    "AnthropicAPIError",
    "AnthropicClientFactory",
    "AnthropicModelDiscovery",
    "AnthropicSecretResolver",
    "BedrockConverseTeacher",
    "BedrockError",
    "DerivedArtifactDisposition",
    "DirectAnthropicTeacher",
    "EnvironmentAnthropicSecretResolver",
    "GenerationSettings",
    "HumanApproverAttestation",
    "ImmutableTeacherCache",
    "IntendedUse",
    "LicenseStatus",
    "LocalOpenWeightTeacher",
    "MacOSKeychainAnthropicSecretResolver",
    "OutputRetention",
    "OutputStorage",
    "OfficialAnthropicClientFactory",
    "PriorityTeacherChain",
    "RedistributionScope",
    "RequestGovernor",
    "ReviewStatus",
    "StudentModelFamily",
    "TeacherBudget",
    "ChainedAnthropicSecretResolver",
    "TeacherCandidate",
    "TeacherError",
    "TeacherErrorCode",
    "TeacherGenerator",
    "TeacherModelFamily",
    "TeacherModelRef",
    "TeacherProvider",
    "TeacherRecipe",
    "TeacherRequest",
    "TeacherResult",
    "ToolSpec",
    "WrittenAuthorizationEvidence",
    "assert_request_allowed",
    "prompt_sha256",
    "request_sha256",
    "seal_license_disposition",
    "seal_output_use_policy",
    "seal_written_authorization",
]
